# Site settings
title: Matthew Rudy Jacobs - Building software and communities
email: me@matthewrudy.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Matthew Rudy Jacobs. But you can just call me Matthew.
  You'll find me on the internet as @matthewrudy.
  I'm from the UK,
  but I've lived in Asia since 2010.

  I want to work with great people, writing great software, to build useful products.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://matthewrudy.com" # the base hostname & protocol for your site
twitter_username: matthewrudy
github_username:  matthewrudy

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap
